### ISSUE TITLE
Problema en generacion de locales

### ISSUE THREAD

**Issue by tomasdelvechio** [redesunlu/netkit-doc#1]
Un estudiante reporta que el script de instalación le decía que no estaban creadas las locales, se las generaba, y luego le volvía a dar el mismo error una y otra vez.

Debuggeando se encontró que la salida de las locales de algunos Debian tienen este formato:

```
$ locale
LANG=es_AR.utf8
LANGUAGE=
LC_CTYPE="es_AR.utf8"
LC_NUMERIC="es_AR.utf8"
LC_TIME="es_AR.utf8"
LC_COLLATE="es_AR.utf8"
LC_MONETARY="es_AR.utf8"
LC_MESSAGES="es_AR.utf8"
LC_PAPER="es_AR.utf8"
LC_NAME="es_AR.utf8"
LC_ADDRESS="es_AR.utf8"
LC_TELEPHONE="es_AR.utf8"
LC_MEASUREMENT="es_AR.utf8"
LC_IDENTIFICATION="es_AR.utf8"
LC_ALL=
```

[La linea que hace ese check](https://github.com/redesunlu/netkit-doc/blob/master/instalar-netkit-ng.sh#L52) no contempla que el string `UTF-8` tenga la forma `utf8`.

Hay que generalizar la condición del if para que acepte ese caso también (Es claro que es un nombre de locale arbitrario, pero no es el primer caso que me cruzo con ese nombre sin guion y en minúsculas).

**Comment by maurom** [comment]
Genial el reporte y la depuración.
Precisamente en el equipo que estoy ahora pasa lo mismo. Ni idea del motivo, pero creo que con esto ya queda resuelto.
Gracias a ambos,

- maurom
