### ISSUE TITLE
Export en bash sin source

### ISSUE THREAD

**Issue by EmmanuelMess** [redesunlu/netkit-doc#7]
Este `export` functiona sin que el script se ejecute con `source`?

https://github.com/redesunlu/netkit-doc/blob/5b3f70864619eb6aa92ea6842ecfa9fda021b564/instalar-netkit-ng.sh#L181

**Comment by maurom** [comment]
Ciertamente, por sí solos no funcionarían. Un `export` no persiste luego de la ejecución del script.

Sin embargo hay una ayuda en la línea 230, la última del archivo.

https://github.com/redesunlu/netkit-doc/blob/5b3f70864619eb6aa92ea6842ecfa9fda021b564/instalar-netkit-ng.sh#L230

No recuerdo bien por qué lo hicimos así, pero creo que venía por lo siguiente: `export` "exporta" las variables indicadas a los hijos del proceso actual, por lo que en teoría, cuando el script de instalación finaliza, el bash que se utilizó para interpretar el script muere y se volvería al shell que se ejecutaba previamente, sin las variables recientemente exportadas. Por eso muchas veces hay que ejecutar `source` o `.` para cargar las nuevas definiciones.

Para evitar eso y permitir que quien instaló netkit pueda utilizar los comandos desde el instante cero, nos tomamos la libertad ejecutar bash al final del script (commit https://github.com/redesunlu/netkit-doc/commit/2e24280a386662aeeb027051914ca10acc6bf65e). Como este bash es un "hijo" del bash padre (en realidad, lo ejecutamos con `exec` para que reemplace al bash que se utilizó para interpretar el script), hereda las variables recién exportadas. 

La ventaja de hacer eso es que deja al entorno netkit listo para usar, y eso para los nuevos usuarios resulta sumamente beneficioso. La desventaja es que se ocupa un poco más de memoria (iniciamos bash dentro de bash) y luego hay que salir con dos exits sucesivos. Es discutible, pero funciona.  

¿Considerás que deberíamos eliminarlos?

Desde luego también agregamos los exports a `.bashrc` para que ya queden definidos en los subsiguientes inicios de sesión.

**Comment by EmmanuelMess** [comment]
> ¿Considerás que deberíamos eliminarlos?

No. Entiendo, gracias.
